[package]
name = "wx-rust-mp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description = "WxRust 公众号模块（对应 weixin-java-mp）"

[lints]
workspace = true

[dependencies]
wx-rust-common.workspace = true
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true }
thiserror = { workspace = true }
regex = "1.11.1"
percent-encoding = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
